### ISSUE TITLE
Hangup adding extension to inkscape

### ISSUE THREAD

**Issue by rdoor** [florianfesti/boxes#126]
Went through the instructions (https://florianfesti.github.io/boxes/html/install/windows.html) with minimal problems, but the final step (python scripts\boxesserver) hung up with a message: serving port 8000. CTL-C gave me 

Traceback (most recent call last):
  File "scripts\boxesserver", line 412, in <module>
    httpd.serve_forever()
  File "C:\Users\RAD\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Users\RAD\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\RAD\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt

Thanks for you support.

**Comment by florianfesti** [comment]
Well, this is expected behavior.  python scripts\boxesserver 
starts a web server which you can access with your browser pointing it at localhost:8000 .
And yes, the command will "hang" as along as the server is running. For the inkscape plugin see the main install page.
