### ISSUE TITLE
TypeError: 'remove_blank_text' is an invalid keyword argument for XMLParser()

### ISSUE THREAD

**Issue by bferrarese** [florianfesti/boxes#163]
Hi there,

I had an old boxes.py working fine and decided to update to take advantage of the optimized paths (#63) but now my boxes.py is not working anymore.

I have linux with inkscape. 
inkscape 0.92.4
lxml 4.4.1
markdown 3.1.1
cairo 1.17.2
python-cairo 1.18.1
python 3.7.4

```
Traceback (most recent call last):
  File "/usr/share/inkscape/extensions/boxes", line 107, in <module>
    main()
  File "/usr/share/inkscape/extensions/boxes", line 47, in main
    run_generator(name, sys.argv[2:])
  File "/usr/share/inkscape/extensions/boxes", line 73, in run_generator
    box.close()
  File "/usr/lib/python3.7/site-packages/boxes-0.1-py3.7.egg/boxes/__init__.py", line 623, in close
  File "/usr/lib/python3.7/site-packages/boxes-0.1-py3.7.egg/boxes/svgutil.py", line 251, in svgMerge
TypeError: 'remove_blank_text' is an invalid keyword argument for XMLParser()
```

Any idea? Thanks

**Comment by florianfesti** [comment]
Cool! Someone actually uses the Inkscape plugins!
This patch should fix the issue. I probably moved to the ElementTree XML lib a bit too quickly.
