### ISSUE TITLE
Can't use Boxes as Inkscape pluging

### ISSUE THREAD

**Issue by jlfrucot** [florianfesti/boxes#622]
**Describe the bug**
After clicking on a boxe generator, receive this 

```
/usr/local/bin/boxes:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('boxes==0.9', 'boxes')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (qrcode 7.4.2 (/usr/lib/python3/dist-packages), Requirement.parse('qrcode==7.3.1'), {'boxes'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/boxes", line 4, in <module>
    __import__('pkg_resources').run_script('boxes==0.9', 'boxes')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qrcode==7.3.1' distribution was not found and is required by boxes
Traceback (most recent call last):
  File "/home/frucot/.config/inkscape/extensions/boxes_proxy.py", line 82, in <module>
    main()
  File "/home/frucot/.config/inkscape/extensions/boxes_proxy.py", line 78, in main
    boxesPyWrapper().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 231, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "/usr/share/inkscape/extensions/inkex/extensions.py", line 234, in effect
    fragment = self.generate()
               ^^^^^^^^^^^^^^^
  File "/home/frucot/.config/inkscape/extensions/boxes_proxy.py", line 66, in generate
    doc = etree.parse(stream, parser=etree.XMLParser(huge_tree=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3541, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1920, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1204, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError
  File "/tmp/boxes.py-inkscape2_4abh43.svg", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/boxes.py-inkscape2_4abh43.svg' mode='r' encoding='UTF-8'>

```

**Additional context**
Running ubuntu 23.10
Python 3.11.6
Inkscape 1.2

The standalone app run fine on localhost:8000

Best regards

**Comment by florianfesti** [comment]
Yeah, we hard coded the version of the qrcode module. Fixed in 013a781050
